[Audio::transcribe] Add support for timestamp_granularities
openai-php/client pull request #335
Opened 2024-02-09 22:27 UTC by jplhomer

### What:

- [ ] Bug Fix
- [x] New Feature

### Description:

This PR adds support for the new [`timestamp_granularities[]` property](https://platform.openai.com/docs/api-reference/audio/createTranscription) in Audio Transcriptions.

- Adds the ability to describe the granularity level of the transcription
- Processes the response to include `words`
- Adjusts the HTTPTransporter `Payload` class to support sending array-based data

Currently, attempting to pass in a granularity level array results in an error:

```php
$response = OpenAI::audio()->transcribe([
  'model' => 'whisper-1',
  'file' => $file
  'response_format' => 'verbose_json',
  'timestamp_granularities' => ['word'],
]);
```

Exception:

```
First argument to "Http\Message\MultipartStream\MultipartStreamBuilder::createStream()" must be a string, resource or StreamInterface.
```

My solution is to parse one level of array data. I'm not sure if this is the best solution, or if we ought to support recursive array parsing.

2024-04-11 22:05 UTC, solomonjames commented
How can we get this merged looked at and merged?

2024-04-11 22:31 UTC, solomonjames requested changes

2024-04-11 22:31 UTC, solomonjames commented on src/ValueObjects/Transporter/Payload.php
> +                            $streamBuilder->addResource($key.'['.$nestedKey.']', $nestedValue);
This didn't work for me using the provided syntax: `'timestamp_granularities' => ['word'],`

For this to work we need to do something like
```suggestion
                            $finalkey = is_int($nestedKey) ? $key.'[]' : $key.'['.$nestedKey.']';
                            $streamBuilder->addResource($finalkey, $nestedValue);
```

2024-04-11 22:37 UTC, solomonjames commented
This looks great overall, and worked for me once I made that small tweak to your code. Thank you for pushing this up, I hope we can get it merged into the main project, as I have it forked just to use this feature.

2024-04-15 19:10 UTC, gehrisandro commented
Resolve here https://github.com/openai-php/client/pull/374

Thanks @jplhomer for your work!

2024-04-15 19:10 UTC, closed without merging