Fix type definition for responses in ClientFake::addResponses method
openai-php/client pull request #382
Opened 2024-04-24 15:14 UTC by ovitores

### What:

- [x ] Bug Fix
- [ ] New Feature

### Description:

Fix type definition in `ClientFake::addResposnses()` method to avoid messages from IDE advertising thhat objects passed are of different type

2024-10-21 10:54 UTC, DjordyKoert commented
any update on when this fix can be expected to be merged?

2025-04-05 10:35 UTC, iBotPeaches approved these changes

2025-04-05 19:03 UTC, iBotPeaches requested changes
Apologies. I was going to merge this, but it fails `composer test:lint`.

2025-04-07 10:05 UTC, iBotPeaches approved these changes

2025-04-07 11:31 UTC, merged