Bytes commerce patch 1
openai-php/client pull request #501
Opened 2024-11-15 10:10 UTC by bytes-commerce

### What:

- [*] Bug Fix
- [ ] New Feature

### Description:

Allow list pages to be queried

### Related:

2025-04-08 23:48 UTC, iBotPeaches requested changes
Unforunately the CI is failing with this.

> PHP Fatal error:  Declaration of OpenAI\Testing\Resources\FilesTestResource::list(): OpenAI\Responses\Files\ListResponse must be compatible with OpenAI\Contracts\Resources\FilesContract::list(array $parameters = []): OpenAI\Responses\Files\ListResponse in /home/runner/work/client/client/src/Testing/Resources/FilesTestResource.php on line 22

I'll take another look when pipeline fixed. Thanks for pr!

2025-04-09 20:38 UTC, bytes-commerce commented
No, thanks, I'll just close it and leave that work open for somebody else. :)

2025-04-09 20:38 UTC, closed without merging

2025-04-09 20:45 UTC, iBotPeaches commented
Okay. I understand it was probably due to the many month delay to review it - apologies for that.

2025-04-15 08:54 UTC, bytes-commerce commented
No bad feelings here, just the lack of time to work on it, I saw that @efpapado took on the matter which is absolutely legit, thanks for taking the care. :rose: